# Generated by Django 4.1.5 on 2023-01-05 18:09

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('C:/Users/fraan/Desktop/practica/Portfolio/backend/media'))),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('frontpage', models.ImageField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('C:/Users/fraan/Desktop/practica/Portfolio/backend/media'))),
                ('frontpageText', models.TextField(blank=True, max_length=255, null=True)),
                ('featureSignIn', models.ImageField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('C:/Users/fraan/Desktop/practica/Portfolio/backend/media'))),
                ('featureSignInText', models.TextField(blank=True, max_length=255, null=True)),
                ('featureDashboard', models.ImageField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('C:/Users/fraan/Desktop/practica/Portfolio/backend/media'))),
                ('featureDashboardText', models.TextField(blank=True, max_length=255, null=True)),
                ('featureCrud', models.ImageField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('C:/Users/fraan/Desktop/practica/Portfolio/backend/media'))),
                ('featureCrudText', models.TextField(blank=True, max_length=255, null=True)),
                ('responsive1', models.ImageField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('C:/Users/fraan/Desktop/practica/Portfolio/backend/media'))),
                ('responsive2', models.ImageField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('C:/Users/fraan/Desktop/practica/Portfolio/backend/media'))),
                ('responsive3', models.ImageField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('C:/Users/fraan/Desktop/practica/Portfolio/backend/media'))),
            ],
        ),
    ]
