# Generated by Django 4.1.5 on 2023-01-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_slug_alter_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\fraan\\Desktop\\practica\\Portfolio\\backend\\mediauploads/'),
        ),
    ]
