# Generated by Django 4.1.5 on 2023-01-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_project_upvotes_project_url_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/gallery/')),
                ('upvotes', models.IntegerField(default=0)),
            ],
        ),
    ]
