# Generated by Django 4.1.5 on 2023-01-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/gallery/video/'),
        ),
    ]
